# Generated by Django 4.2.1 on 2023-05-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('produkt_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_dostepna', models.FloatField(default=0.0)),
                ('nazwa_produktu', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
    ]
