# Generated by Django 4.2.1 on 2023-05-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazynier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazyn',
            new_name='Produkty',
        ),
    ]
