# Generated by Django 4.2.1 on 2023-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazynier', '0002_rename_magazyn_produkty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='nazwa_produktu',
            field=models.CharField(default='', max_length=30),
        ),
    ]
