# Generated by Django 4.2.1 on 2023-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przepisy',
            fields=[
                ('przepis_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_przepisu', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skladniki',
            fields=[
                ('krotka_id', models.AutoField(primary_key=True, serialize=False)),
                ('przepis_id', models.IntegerField()),
                ('produkt_id', models.IntegerField()),
                ('ilosc_produktu', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('przepis_id', 'produkt_id')},
            },
        ),
    ]
